type: "conf"
save_path: "ckpt/solid-conf"

flow_model: "config/solid-flow.yaml"

train_base_folder: "../dataset/mbs-shapewhole"
val_base_folder: "../dataset/mbs-shapewhole"

epochs: 50
batch_size: 32

lr: 1.0e-3
lr_decay: 0.7
lr_clip: 1.0e-5

bn_momentum: 0.9
bn_decay: 0.5
weight_decay: 0.0
decay_step: 200000
